<?xml version="1.0"?>
<robot name="vineyard_mower" xmlns:xacro="http://www.ros.org/wiki/xacro">
  
  <!-- Properties -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  
  <!-- Robot dimensions -->
  <xacro:property name="base_width" value="1.5"/>
  <xacro:property name="base_length" value="0.5"/>
  <xacro:property name="base_height" value="0.2"/>
  <xacro:property name="robot_height" value="0.5"/>
  
  <!-- Wheel properties -->
  <xacro:property name="wheel_radius" value="0.15"/>
  <xacro:property name="wheel_width" value="0.3"/>
  <xacro:property name="track_width" value="1.4"/>
  
  <!-- Sensor properties -->
  <xacro:property name="sensor_height" value="0.1"/>
  
  <!-- Materials -->
  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>
  
  <material name="dark_grey">
    <color rgba="0.2 0.2 0.2 1.0"/>
  </material>
  
  <material name="orange">
    <color rgba="1.0 0.423529411765 0.0392156862745 1.0"/>
  </material>
  
  <material name="grey">
    <color rgba="0.2 0.2 0.2 1.0"/>
  </material>
  
  <material name="red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>
  
  <material name="blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <mass value="50.0"/>
      <inertia ixx="7.58333" ixy="0.0" ixz="0.0" iyy="7.58333" iyz="0.0" izz="9.375"/>
    </inertial>
  </link>

  <!-- Upper chassis for sensors -->
  <link name="upper_chassis">
    <visual>
      <origin xyz="0 0 ${(robot_height - base_height)/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length*0.6} ${base_width*0.6} ${robot_height - base_height}"/>
      </geometry>
      <material name="grey"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 ${(robot_height - base_height)/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length*0.6} ${base_width*0.6} ${robot_height - base_height}"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 ${(robot_height - base_height)/2}" rpy="0 0 0"/>
      <mass value="10.0"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>

  <joint name="upper_chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="upper_chassis"/>
    <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
  </joint>

  <!-- Left track wheel -->
  <link name="left_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <mass value="5.0"/>
      <inertia ixx="0.1125" ixy="0" ixz="0" iyy="0.1125" iyz="0" izz="0.1125"/>
    </inertial>
  </link>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="0 ${track_width/2} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Right track wheel -->
  <link name="right_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <mass value="5.0"/>
      <inertia ixx="0.1125" ixy="0" ixz="0" iyy="0.1125" iyz="0" izz="0.1125"/>
    </inertial>
  </link>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="0 ${-track_width/2} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Sensor mount (center of robot) -->
  <link name="sensor_mount">
    <visual>
      <origin xyz="0 0 ${sensor_height/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="${sensor_height}"/>
      </geometry>
      <material name="dark_grey"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 ${sensor_height/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="${sensor_height}"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 ${sensor_height/2}" rpy="0 0 0"/>
      <mass value="1.0"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>

  <joint name="sensor_mount_joint" type="fixed">
    <parent link="upper_chassis"/>
    <child link="sensor_mount"/>
    <origin xyz="0 0 ${(robot_height - base_height)/2 + sensor_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- LiDAR sensor -->
  <link name="lidar_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.04" length="0.05"/>
      </geometry>
      <material name="red"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.04" length="0.05"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.5"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="sensor_mount"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 ${sensor_height + 0.025}" rpy="0 0 0"/>
  </joint>

  <!-- Front camera (Intel RealSense) -->
  <link name="front_camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.09 0.025 0.025"/>
      </geometry>
      <material name="blue"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.09 0.025 0.025"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.15"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="front_camera_joint" type="fixed">
    <parent link="upper_chassis"/>
    <child link="front_camera_link"/>
    <origin xyz="${base_length*0.3} 0 ${(robot_height - base_height)/4}" rpy="0 0 0"/>
  </joint>

  <!-- Rear camera (Intel RealSense) -->
  <link name="rear_camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.09 0.025 0.025"/>
      </geometry>
      <material name="blue"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.09 0.025 0.025"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.15"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="rear_camera_joint" type="fixed">
    <parent link="upper_chassis"/>
    <child link="rear_camera_link"/>
    <origin xyz="${-base_length*0.3} 0 ${(robot_height - base_height)/4}" rpy="0 0 ${PI}"/>
  </joint>

  <!-- Gazebo plugins and properties -->
  <gazebo reference="base_link">
    <material>Gazebo/Orange</material>
  </gazebo>
  
  <gazebo reference="upper_chassis">
    <material>Gazebo/Grey</material>
  </gazebo>
  
  <gazebo reference="left_wheel">
    <material>Gazebo/Black</material>
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>1000000.0</kp>
    <kd>100.0</kd>
    <minDepth>0.001</minDepth>
    <maxVel>1.0</maxVel>
    <fdir1>1 0 0</fdir1>
  </gazebo>
  
  <gazebo reference="right_wheel">
    <material>Gazebo/Black</material>
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>1000000.0</kp>
    <kd>100.0</kd>
    <minDepth>0.001</minDepth>
    <maxVel>1.0</maxVel>
    <fdir1>1 0 0</fdir1>
  </gazebo>

  <gazebo reference="lidar_link">
    <material>Gazebo/Red</material>
  </gazebo>

  <gazebo reference="front_camera_link">
    <material>Gazebo/Blue</material>
  </gazebo>

  <gazebo reference="rear_camera_link">
    <material>Gazebo/Blue</material>
  </gazebo>

  <!-- Differential drive plugin for Gz -->
  <gazebo>
    <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
      <left_joint>left_wheel_joint</left_joint>
      <right_joint>right_wheel_joint</right_joint>
      <wheel_separation>${track_width}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>
      <odom_publish_frequency>1</odom_publish_frequency>
      <topic>cmd_vel</topic>
      <odom_topic>odom</odom_topic>
      <tf_topic>/tf</tf_topic>
      <frame_id>odom</frame_id>
      <child_frame_id>base_link</child_frame_id>
    </plugin>
  </gazebo>

</robot>
